# Use Nginx to serve the static files
FROM nginx:alpine

# Copy the static frontend files to the default Nginx public directory
COPY . /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80